apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dxia-nginx-deployment
  namespace: dxia
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/operation-covfefe-1/dxia-nginx
        ports:
        - containerPort: 80
